Repository powerflows/powerflows-dmn, pull requests merged in 2019-03, with the labels that each got.

#153 Added FEEL evaluation support to decision engine. Resolved #138
  src/main/java/org/powerflows/dmn/engine/configuration/DefaultDecisionEngineConfiguration.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/ExpressionEvaluationConfiguration.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProvider.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProviderFactory.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/JuelExpressionEvaluationProvider.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/MvelExpressionEvaluationProvider.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/ScriptEngineExpressionEvaluationProvider.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/ExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelCollectionExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelComparisonExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelEqualExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelFunctionExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelNotExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelRangeExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelUnaryExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/function/DateAndTime.java
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/GroovyExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/JavascriptExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/JuelExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/MvelExpressionEvaluationProviderSpec.groovy
  src/test/resources/org/powerflows/dmn/engine/configuration/reference-single.yml
Labels: enhancement

#154 Develop
  src/main/java/org/powerflows/dmn/engine/configuration/DefaultDecisionEngineConfiguration.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/ExpressionEvaluationConfiguration.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProvider.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProviderFactory.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/JuelExpressionEvaluationProvider.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/MvelExpressionEvaluationProvider.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/ScriptEngineExpressionEvaluationProvider.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/ExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelCollectionExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelComparisonExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelEqualExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelFunctionExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelNotExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelRangeExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelUnaryExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/function/DateAndTime.java
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/GroovyExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/JavascriptExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/JuelExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/MvelExpressionEvaluationProviderSpec.groovy
  src/test/resources/org/powerflows/dmn/engine/configuration/reference-single.yml
Labels: enhancement

#159 Type converters can not convert null values. Fixed #155
  src/main/java/org/powerflows/dmn/engine/evaluator/type/converter/BooleanConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/type/converter/DoubleConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/type/converter/IntegerConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/type/converter/StringConverter.java
  src/test/groovy/org/powerflows/dmn/engine/evaluator/type/converter/BooleanConverterSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/type/converter/DoubleConverterSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/type/converter/IntegerConverterSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/type/converter/StringConverterSpec.groovy
Labels: bug

#160 Rule builder can not build object if no input entries. Fixed #156
  src/main/java/org/powerflows/dmn/engine/model/decision/rule/Rule.java
  src/main/java/org/powerflows/dmn/io/yaml/YamlDecisionConverter.java
  src/test/groovy/org/powerflows/dmn/io/xml/XmlDecisionReaderSpec.groovy
  src/test/groovy/org/powerflows/dmn/io/yaml/YamlDecisionReaderSpec.groovy
  src/test/resources/org/powerflows/dmn/io/xml/camunda-dmn-1.1-example.dmn
  src/test/resources/org/powerflows/dmn/io/yaml/test-multiple-decisions.yml
  src/test/resources/org/powerflows/dmn/io/yaml/test-single-decision.yml
Labels: bug

#161 Decision builder can not build object if no inputs. Fixed #157
  src/main/java/org/powerflows/dmn/engine/model/decision/Decision.java
  src/main/java/org/powerflows/dmn/io/yaml/YamlDecisionConverter.java
  src/test/groovy/org/powerflows/dmn/io/xml/XmlDecisionReaderSpec.groovy
  src/test/groovy/org/powerflows/dmn/io/yaml/YamlDecisionReaderSpec.groovy
  src/test/resources/org/powerflows/dmn/io/xml/camunda-dmn-1.1-example-no-inputs.dmn
  src/test/resources/org/powerflows/dmn/io/yaml/test-single-decision-no-inputs.yml
Labels: bug

#162 Name alias is set to empty string if input variable is empty. Fixed #158
  src/main/java/org/powerflows/dmn/io/xml/XMLDecisionConverter.java
  src/test/groovy/org/powerflows/dmn/io/xml/XmlDecisionReaderSpec.groovy
  src/test/resources/org/powerflows/dmn/io/xml/camunda-dmn-1.1-example-empty-input-variable.dmn
Labels: bug

#164 Added FEEL evaluation for output entry. Resolved #163
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProvider.java
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProviderSpec.groovy
Labels: enhancement

#166 Decision variables validator raises an error for literals in FEEL. Re…
  src/main/java/org/powerflows/dmn/engine/evaluator/decision/DecisionEvaluator.java
Labels: bug

#169 Output entry should be created with null value if exists in OMG 1.1 X…
  src/main/java/org/powerflows/dmn/io/xml/XMLDecisionConverter.java
  src/test/groovy/org/powerflows/dmn/io/xml/XmlDecisionReaderSpec.groovy
Labels: bug

#171 Input and output entry for FEEL should be evaluated in the same way a…
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProvider.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelCollectionExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelComparisonExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelEqualExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelNotExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelRangeExpressionConverter.java
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProviderSpec.groovy
Labels: bug

#173 Covered by unit tests evaluation cases with literal strings for all e…
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/GroovyExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/JavascriptExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/JuelExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/MvelExpressionEvaluationProviderSpec.groovy
Labels: enhancement

#174 Added some Javadoc documentation. Resolved #167
  src/main/java/org/powerflows/dmn/engine/DecisionEngine.java
  src/main/java/org/powerflows/dmn/engine/configuration/DecisionEngineConfiguration.java
  src/main/java/org/powerflows/dmn/engine/configuration/DefaultDecisionEngineConfiguration.java
  src/main/java/org/powerflows/dmn/engine/evaluator/context/EvaluationContext.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/AbstractMethodBinding.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/BoundMethod.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/InstanceMethodBinding.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/MethodBinding.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/StaticMethodBinding.java
  src/main/java/org/powerflows/dmn/engine/model/decision/Decision.java
  src/main/java/org/powerflows/dmn/engine/model/decision/EvaluationMode.java
  src/main/java/org/powerflows/dmn/engine/model/decision/HitPolicy.java
  src/main/java/org/powerflows/dmn/engine/model/decision/expression/ExpressionType.java
  src/main/java/org/powerflows/dmn/engine/model/decision/rule/Rule.java
  src/main/java/org/powerflows/dmn/engine/model/evaluation/result/DecisionResult.java
  src/main/java/org/powerflows/dmn/engine/model/evaluation/variable/DecisionVariables.java
  src/main/java/org/powerflows/dmn/engine/package-info.java
  src/main/java/org/powerflows/dmn/engine/reader/DecisionReader.java
  src/main/java/org/powerflows/dmn/engine/writer/DecisionWriter.java
  src/main/java/org/powerflows/dmn/io/package-info.java
  src/main/java/org/powerflows/dmn/io/xml/package-info.java
  src/main/java/org/powerflows/dmn/io/yaml/package-info.java
Labels: enhancement

#175 Develop
  src/main/java/org/powerflows/dmn/engine/DecisionEngine.java
  src/main/java/org/powerflows/dmn/engine/configuration/DecisionEngineConfiguration.java
  src/main/java/org/powerflows/dmn/engine/configuration/DefaultDecisionEngineConfiguration.java
  src/main/java/org/powerflows/dmn/engine/evaluator/context/EvaluationContext.java
  src/main/java/org/powerflows/dmn/engine/evaluator/decision/DecisionEvaluator.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProvider.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/AbstractMethodBinding.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/BoundMethod.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/InstanceMethodBinding.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/MethodBinding.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/StaticMethodBinding.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelCollectionExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelComparisonExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelEqualExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelNotExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/feel/converter/mvel/FeelToMvelRangeExpressionConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/type/converter/BooleanConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/type/converter/DoubleConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/type/converter/IntegerConverter.java
  src/main/java/org/powerflows/dmn/engine/evaluator/type/converter/StringConverter.java
  src/main/java/org/powerflows/dmn/engine/model/decision/Decision.java
  src/main/java/org/powerflows/dmn/engine/model/decision/EvaluationMode.java
  src/main/java/org/powerflows/dmn/engine/model/decision/HitPolicy.java
  src/main/java/org/powerflows/dmn/engine/model/decision/expression/ExpressionType.java
  src/main/java/org/powerflows/dmn/engine/model/decision/rule/Rule.java
  src/main/java/org/powerflows/dmn/engine/model/evaluation/result/DecisionResult.java
  src/main/java/org/powerflows/dmn/engine/model/evaluation/variable/DecisionVariables.java
  src/main/java/org/powerflows/dmn/engine/package-info.java
  src/main/java/org/powerflows/dmn/engine/reader/DecisionReader.java
  src/main/java/org/powerflows/dmn/engine/writer/DecisionWriter.java
  src/main/java/org/powerflows/dmn/io/package-info.java
  src/main/java/org/powerflows/dmn/io/xml/XMLDecisionConverter.java
  src/main/java/org/powerflows/dmn/io/xml/package-info.java
  src/main/java/org/powerflows/dmn/io/yaml/YamlDecisionConverter.java
  src/main/java/org/powerflows/dmn/io/yaml/package-info.java
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/FeelExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/GroovyExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/JavascriptExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/JuelExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/expression/provider/MvelExpressionEvaluationProviderSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/type/converter/BooleanConverterSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/type/converter/DoubleConverterSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/type/converter/IntegerConverterSpec.groovy
  src/test/groovy/org/powerflows/dmn/engine/evaluator/type/converter/StringConverterSpec.groovy
  src/test/groovy/org/powerflows/dmn/io/xml/XmlDecisionReaderSpec.groovy
  src/test/groovy/org/powerflows/dmn/io/yaml/YamlDecisionReaderSpec.groovy
  src/test/resources/org/powerflows/dmn/io/xml/camunda-dmn-1.1-example-empty-input-variable.dmn
  src/test/resources/org/powerflows/dmn/io/xml/camunda-dmn-1.1-example-no-inputs.dmn
  src/test/resources/org/powerflows/dmn/io/xml/camunda-dmn-1.1-example.dmn
  src/test/resources/org/powerflows/dmn/io/yaml/test-multiple-decisions.yml
  src/test/resources/org/powerflows/dmn/io/yaml/test-single-decision-no-inputs.yml
  src/test/resources/org/powerflows/dmn/io/yaml/test-single-decision.yml
Labels: bug, enhancement

#178 Fix uncompilable JavaDocs. Fixed #176
  src/main/java/org/powerflows/dmn/engine/DecisionEngine.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/MethodBinding.java
  src/main/java/org/powerflows/dmn/io/xml/package-info.java
  src/main/java/org/powerflows/dmn/io/yaml/package-info.java
Labels: bug

#179 Generated JavaDocs during regular build - not only if mvn:perform pha…
  pom.xml
Labels: enhancement

#181 Develop
  pom.xml
  src/main/java/org/powerflows/dmn/engine/DecisionEngine.java
  src/main/java/org/powerflows/dmn/engine/evaluator/expression/provider/binding/MethodBinding.java
  src/main/java/org/powerflows/dmn/io/xml/package-info.java
  src/main/java/org/powerflows/dmn/io/yaml/package-info.java
Labels: bug, enhancement

#186 Added evaluation tests for rules defined in yaml file with FEEL and J…
  src/test/groovy/org/powerflows/dmn/engine/configuration/DefaultDecisionEngineConfigurationFeelAndJuelSpec.groovy
  src/test/resources/org/powerflows/dmn/engine/configuration/reference-single-feel-and-juel.yml
Labels: enhancement

#189 Can not save to YAML file if no input entries. Fixed #187
  src/main/java/org/powerflows/dmn/io/yaml/YamlDecisionConverter.java
Labels: bug

#190 Upgraded version of dependent libraries. Resolved #184
  pom.xml
Labels: enhancement

#193 Build failed on Java 9 or newer. Fixed #192
  pom.xml
Labels: bug

#194 Updated README.md file. Resolved #188
  README.md
Labels: enhancement

#196 Prepared pom.xml file for 1.0.0 release. Resolved #195
  pom.xml
Labels: enhancement

#198 Fixed examples of building decision model in java. Resolved #183
  README.md
Labels: bug

#199 Updated README.md file. Resolved #183
  README.md
Labels: enhancement
